<?php

return [
    'active'         => 1,
    'super_admin_id' => 1,
    'develop_id'     => 2,
    'super_admin'    => 'Quản trị viên cấp cao',
    'image_type'     => 0,
    'video_type'     => 1,
    'disabled'       => 1,
    'enabled'        => 0,
    'active'         => 1,
    'inactive'       => 0,
    'roles' => [
        'list',
        'create',
        'edit',
        'delete',
    ],
    'role_name'  => [
        'user'      => 'user',
        'role'      => 'role',
        'blog'      => 'blog',
        'banner'    => 'banner',
        'category'  => 'category',
        'brand'     => 'brand',
        'order'     => 'order',
        'revenue'   => 'revenue',
        'product'   => 'product',
    ],
    'status_order' => [
        'cancelled'  => -1,
        'pending'    => 0,
        'shipped'    => 1,
        'in_transit' => 2,
        'delivered'  => 3,
        'success'    => 4,
    ],
    'payment_type' => [
        'cod'    => 0,
        'vnpay'  => 1,
        'momo'   => 2,
    ],
    'status_payment' => [
        'unpaid'  => 0,
        'paid'    => 1,
    ],
    'type_coupon' => [
        'percent'    => 0,
        'numeric'    => 1,
    ],
    'type_coupon_common' => [
        0    => "Phần trăm",
        1    => "Tiền",
    ],
    'status_order_common' => [
        -1   => 'Hủy đơn',
        0    => 'Đang đợi xác nhận',
        1    => 'Xác nhận đơn hàng',
        2    => 'Đang giao hàng',
        3    => 'Đã giao hàng',
        4    => 'Hoàn thành',
    ],
    'className' => [
        -1   => ' rounded-sm border border-red-500 text-red-500',
        0    => ' rounded-sm border border-sky-500 text-sky-500',
        1    => ' rounded-sm border border-sky-500 text-sky-500',
        2    => ' rounded-sm border border-sky-500 text-sky-500',
        3    => ' rounded-sm border border-green-500 text-green-500',
        4    => ' rounded-sm border border-green-500 text-green-500',
    ],
    'classNameTypePayment' => [
        0    => ' rounded-sm border border-rose-500 text-rose-500',
        1    => ' rounded-sm border border-cyan-500 text-cyan-500',
        2    => ' rounded-sm border border-fuchsia-600 text-fuchsia-600',
    ],
    'classNameStatusPayment' => [
        0    => ' rounded-sm border border-orange-500 text-orange-500',
        1    => ' rounded-sm border border-sky-500 text-sky-500',
    ],
    'payment_type_common' => [
        0    => 'COD',
        1    => 'VNPAY',
        2    => 'MOMO',
    ],
    'status_payment_common' => [
        0    => "Chưa thanh toán",
        1    => "Đã thanh toán",
    ],
    'App\Models\User'      => 'User',
    'App\Models\Role'      => 'Role',
    'App\Models\Blog'      => 'Blog',
    'App\Models\Banner'    => 'Banner',
    'App\Models\Revenue'   => 'Revenue',
    'App\Models\Product'   => 'Product',
    'App\Models\Order'     => 'Order',
    'App\Models\Category'  => 'Category',
    'App\Models\Brand'     => 'Brand',
];
