<?php

return [
    'active'         => 1,
    'super_admin_id' => 1,
    'develop_id'     => 2,
    'super_admin'    => 'Quản trị viên cấp cao',
    'image_type'     => 0,
    'video_type'     => 1,
    'disabled'       => 1,
    'enabled'        => 0,
    'active'         => 1,
    'inactive'       => 0,
    'roles' => [
        'list',
        'create',
        'edit',
        'delete',
    ],
    'role_name'  => [
        'user'      => 'user',
        'role'      => 'role',
        'blog'      => 'blog',
        'banner'    => 'banner',
        'category'  => 'category',
        'brand'     => 'brand',
        'order'     => 'order',
        'revenue'   => 'revenue',
        'product'   => 'product',
    ],
    'App\Models\User'      => 'User',
    'App\Models\Role'      => 'Role',
    'App\Models\Blog'      => 'Blog',
    'App\Models\Banner'    => 'Banner',
    'App\Models\Revenue'   => 'Revenue',
    'App\Models\Product'   => 'Product',
    'App\Models\Order'     => 'Order',
    'App\Models\Category'  => 'Category',
    'App\Models\Brand'     => 'Brand',
];
